
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class Main1 extends javax.swing.JFrame {

    /**
     * Creates new form Main1
     */
    public Main1() {
        initComponents();
        setResizable(false);
    }
    
    public void my_update(String st1) {
		jTextField1.setText(st1);
                //jTextField2.setText(str2);
	}
     public void re(String st1) {
		jTextField2.setText(st1);
                //jTextField2.setText(str2);
	}
     
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jt3 = new javax.swing.JTextField();
        jt4 = new javax.swing.JTextField();
        jt5 = new javax.swing.JTextField();
        jt7 = new javax.swing.JTextField();
        jt6 = new javax.swing.JTextField();
        jt8 = new javax.swing.JTextField();
        jt9 = new javax.swing.JTextField();
        jt10 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jComboBox8 = new javax.swing.JComboBox<>();
        jt19 = new javax.swing.JTextField();
        jt20 = new javax.swing.JTextField();
        jt21 = new javax.swing.JTextField();
        jt23 = new javax.swing.JTextField();
        jt22 = new javax.swing.JTextField();
        jt24 = new javax.swing.JTextField();
        jt25 = new javax.swing.JTextField();
        jt26 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jt1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(238, 241, 255));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(10, 38, 71));
        jLabel1.setText("Semester1");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(20, 66, 114));
        jLabel4.setText("Subject Name");

        jLabel9.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(32, 82, 149));
        jLabel9.setText("Computer Programming");

        jLabel10.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(32, 82, 149));
        jLabel10.setText("Basic Electrical And Electronic Engineering");

        jLabel11.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(32, 82, 149));
        jLabel11.setText("Basic Electrical And Electronic Engineering Laboratory");

        jLabel12.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(32, 82, 149));
        jLabel12.setText("Engineering Graphics");

        jLabel13.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(32, 82, 149));
        jLabel13.setText("Mathematics For Engineers");

        jLabel14.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(32, 82, 149));
        jLabel14.setText("Soft Skills-1");

        jLabel15.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(32, 82, 149));
        jLabel15.setText("Engineering Physics");

        jLabel16.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(32, 82, 149));
        jLabel16.setText("Engineering Physics Laboratory");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/letter-c.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/motor.png"))); // NOI18N
        jLabel25.setText("jLabel25");

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineering.png"))); // NOI18N
        jLabel26.setText("jLabel26");

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p1.png"))); // NOI18N
        jLabel27.setText("jLabel27");

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maths.png"))); // NOI18N
        jLabel28.setText("jLabel28");

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soft-skills.png"))); // NOI18N
        jLabel29.setText("jLabel29");

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/physics.png"))); // NOI18N
        jLabel30.setText("jLabel30");

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wave.png"))); // NOI18N
        jLabel31.setText("jLabel31");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(20, 66, 114));
        jLabel5.setText("Subject Code");

        jLabel17.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(32, 82, 149));
        jLabel17.setText("CSE101");

        jLabel18.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(32, 82, 149));
        jLabel18.setText("ECE131");

        jLabel19.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(32, 82, 149));
        jLabel19.setText("ECE132");

        jLabel20.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(32, 82, 149));
        jLabel20.setText("MEC103");

        jLabel21.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(32, 82, 149));
        jLabel21.setText("MTH165");

        jLabel22.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(32, 82, 149));
        jLabel22.setText("PES318");

        jLabel23.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(32, 82, 149));
        jLabel23.setText("PHY109");

        jLabel24.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(32, 82, 149));
        jLabel24.setText("PHY119");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(20, 66, 114));
        jLabel6.setText("Marks");

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(20, 66, 114));
        jLabel7.setText("Credit");

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(20, 66, 114));
        jLabel8.setText("Grade");

        jt3.setBackground(new java.awt.Color(238, 241, 255));
        jt3.setFont(new java.awt.Font("Segoe UI Variable", 3, 12)); // NOI18N
        jt3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));

        jt4.setBackground(new java.awt.Color(238, 241, 255));
        jt4.setFont(new java.awt.Font("Segoe UI Variable", 3, 12)); // NOI18N
        jt4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        jt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt4ActionPerformed(evt);
            }
        });

        jt5.setBackground(new java.awt.Color(238, 241, 255));
        jt5.setFont(new java.awt.Font("Segoe UI Variable", 3, 12)); // NOI18N
        jt5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        jt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt5ActionPerformed(evt);
            }
        });

        jt7.setBackground(new java.awt.Color(238, 241, 255));
        jt7.setFont(new java.awt.Font("Segoe UI Variable", 3, 12)); // NOI18N
        jt7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        jt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt7ActionPerformed(evt);
            }
        });

        jt6.setBackground(new java.awt.Color(238, 241, 255));
        jt6.setFont(new java.awt.Font("Segoe UI Variable", 3, 12)); // NOI18N
        jt6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        jt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt6ActionPerformed(evt);
            }
        });

        jt8.setBackground(new java.awt.Color(238, 241, 255));
        jt8.setFont(new java.awt.Font("Segoe UI Variable", 3, 12)); // NOI18N
        jt8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));

        jt9.setBackground(new java.awt.Color(238, 241, 255));
        jt9.setFont(new java.awt.Font("Segoe UI Variable", 3, 12)); // NOI18N
        jt9.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));

        jt10.setBackground(new java.awt.Color(238, 241, 255));
        jt10.setFont(new java.awt.Font("Segoe UI Variable", 3, 12)); // NOI18N
        jt10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));

        jComboBox1.setBackground(new java.awt.Color(238, 241, 255));
        jComboBox1.setFont(new java.awt.Font("Segoe UI Variable", 3, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jComboBox2.setBackground(new java.awt.Color(238, 241, 255));
        jComboBox2.setFont(new java.awt.Font("Segoe UI Variable", 3, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        jComboBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jComboBox3.setBackground(new java.awt.Color(238, 241, 255));
        jComboBox3.setFont(new java.awt.Font("Segoe UI Variable", 3, 12)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        jComboBox3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jComboBox4.setBackground(new java.awt.Color(238, 241, 255));
        jComboBox4.setFont(new java.awt.Font("Segoe UI Variable", 3, 12)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        jComboBox4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jComboBox5.setBackground(new java.awt.Color(238, 241, 255));
        jComboBox5.setFont(new java.awt.Font("Segoe UI Variable", 3, 12)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        jComboBox5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jComboBox6.setBackground(new java.awt.Color(238, 241, 255));
        jComboBox6.setFont(new java.awt.Font("Segoe UI Variable", 3, 12)); // NOI18N
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        jComboBox6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });

        jComboBox7.setBackground(new java.awt.Color(238, 241, 255));
        jComboBox7.setFont(new java.awt.Font("Segoe UI Variable", 3, 12)); // NOI18N
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        jComboBox7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jComboBox8.setBackground(new java.awt.Color(238, 241, 255));
        jComboBox8.setFont(new java.awt.Font("Segoe UI Variable", 3, 12)); // NOI18N
        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        jComboBox8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jt19.setBackground(new java.awt.Color(238, 241, 255));
        jt19.setFont(new java.awt.Font("Segoe UI Variable", 3, 12)); // NOI18N
        jt19.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));

        jt20.setBackground(new java.awt.Color(238, 241, 255));
        jt20.setFont(new java.awt.Font("Segoe UI Variable", 3, 12)); // NOI18N
        jt20.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        jt20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt20ActionPerformed(evt);
            }
        });

        jt21.setBackground(new java.awt.Color(238, 241, 255));
        jt21.setFont(new java.awt.Font("Segoe UI Variable", 3, 12)); // NOI18N
        jt21.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));

        jt23.setBackground(new java.awt.Color(238, 241, 255));
        jt23.setFont(new java.awt.Font("Segoe UI Variable", 3, 12)); // NOI18N
        jt23.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        jt23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt23ActionPerformed(evt);
            }
        });

        jt22.setBackground(new java.awt.Color(238, 241, 255));
        jt22.setFont(new java.awt.Font("Segoe UI Variable", 3, 12)); // NOI18N
        jt22.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));

        jt24.setBackground(new java.awt.Color(238, 241, 255));
        jt24.setFont(new java.awt.Font("Segoe UI Variable", 3, 12)); // NOI18N
        jt24.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));

        jt25.setBackground(new java.awt.Color(238, 241, 255));
        jt25.setFont(new java.awt.Font("Segoe UI Variable", 3, 12)); // NOI18N
        jt25.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));

        jt26.setBackground(new java.awt.Color(238, 241, 255));
        jt26.setFont(new java.awt.Font("Segoe UI Variable", 3, 12)); // NOI18N
        jt26.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));

        jLabel2.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(20, 66, 114));
        jLabel2.setText("GPA");

        jt1.setBackground(new java.awt.Color(238, 241, 255));
        jt1.setFont(new java.awt.Font("Segoe UI Variable", 3, 18)); // NOI18N
        jt1.setForeground(new java.awt.Color(153, 0, 0));
       // jt1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, null));

        jButton1.setBackground(new java.awt.Color(188, 206, 248));
        jButton1.setText("Calculate GPA");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(188, 206, 248));
        jButton2.setText("Next");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jt6, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                        .addComponent(jt7)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jt5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jt4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jt8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(77, 77, 77)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jt9, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                        .addComponent(jt10)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jt3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(148, 148, 148)))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jt19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jt20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jt21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jt22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jt24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jt26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jt25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jt23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(15, 15, 15))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jt1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(30, 30, 30))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel17)
                    .addComponent(jt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel18)
                    .addComponent(jt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel19)
                    .addComponent(jt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel20)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel22)
                    .addComponent(jt8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel30)
                    .addComponent(jLabel23)
                    .addComponent(jt9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel31)
                        .addComponent(jLabel24)
                        .addComponent(jt10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jt26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton2))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt4ActionPerformed

    private void jt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String a1,a2,a3,a4,a5,a6,a7,a8;
        int g1,g2,g3,g4,g5,g6,g7,g8;
        a1=jComboBox1.getSelectedItem().toString();
        g1=Integer.parseInt(a1);
        a2=jComboBox2.getSelectedItem().toString();
        g2=Integer.parseInt(a1);
        a3=jComboBox3.getSelectedItem().toString();
        g3=Integer.parseInt(a1);
        a4=jComboBox4.getSelectedItem().toString();
        g4=Integer.parseInt(a1);
        a5=jComboBox5.getSelectedItem().toString();
        g5=Integer.parseInt(a1);
        a6=jComboBox6.getSelectedItem().toString();
        g6=Integer.parseInt(a1);
        a7=jComboBox7.getSelectedItem().toString();
        g7=Integer.parseInt(a1);
        a8=jComboBox8.getSelectedItem().toString();
        g8=Integer.parseInt(a1);
        
        
        String m1,m2,m3,m4,m5,m6,m7,m8;
        m1=jt3.getText();
        m2=jt4.getText();
        m3=jt5.getText();
        m4=jt6.getText();
        m5=jt7.getText();
        m6=jt8.getText();
        m7=jt9.getText();
        m8=jt10.getText();
        if(m1.equals("") || m2.equals("") || m3.equals("") || m4.equals("") || m5.equals("") || m6.equals("") || m7.equals("") || m8.equals("")){
            JOptionPane.showMessageDialog(null, "ENTER MARKS", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
        int n1=Integer.parseInt(m1);
        int n2=Integer.parseInt(m2);
        int n3=Integer.parseInt(m3);
        int n4=Integer.parseInt(m4);
        int n5=Integer.parseInt(m5);
        int n6=Integer.parseInt(m6);
        int n7=Integer.parseInt(m7);
        int n8=Integer.parseInt(m8);
        if(n1>100 || n2>100 || n3>100 || n4>100 || n5>100 || n6>100 || n7>100 || n8>100){
            JOptionPane.showMessageDialog(null, "INVALID MARKS", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
        float p1,p2,p3,p4,p5,p6,p7,p8;
       
        float res;
        if(n1>=90){
            jt19.setText("O");
             p1=g1*10;
        }
        else if(n1<90 && n1>=80 ){
            jt19.setText("A+");
            p1=g1*9;
        }
        
        else if(n1<80 && n1>=70 ){
            jt19.setText("A");
             p1=g1*8;
        }
        else if(n1<70 && n1>=60 ){
            jt19.setText("B+");
             p1=g1*7;
        }
        else if(n1<60 && n1>=50 ){
            jt19.setText("B");
             p1=g1*6;
        }
        else if(n1<50 && n1>=40 ){
            jt19.setText("C+");
             p1=g1*5;
        }
        else{
            jt19.setText("E");
             p1=g1*0;
        }
        
        if(n2>=90){
            jt20.setText("O");
             p2=g2*10;
        }
        else if(n2<90 && n2>=80 ){
            jt20.setText("A+");
             p2=g2*9;
        }
       
        else if(n2<80 && n2>=70 ){
            jt20.setText("A");
             p2=g2*8;
        }
        else if(n2<70 && n2>=60 ){
            jt20.setText("B+");
             p2=g2*7;
        }
        else if(n2<60 && n2>=50 ){
            jt20.setText("B");
             p2=g2*6;
        }
        else if(n2<50 && n2>=40 ){
            jt20.setText("C+");
             p2=g2*5;
        }
        else{
            jt20.setText("E");
             p2=g2*0;
        }
        
        if(n3>=90){
            jt21.setText("O");
            p3=g3*10;
        }
        else if(n3<90 && n3>=80 ){
            jt21.setText("A+");
            p3=g3*9;
        }
        
        else if(n3<80 && n3>=70 ){
            jt21.setText("A");
            p3=g3*8;
        }
        else if(n3<70 && n3>=60 ){
            jt21.setText("B+");
            p3=g3*7;
        }
        else if(n3<60 && n3>=50 ){
            jt21.setText("B");
            p3=g3*6;
        }
        else if(n3<50 && n3>=40 ){
            jt21.setText("C+");
            p3=g3*5;
        }
        else{
            jt21.setText("E");
            p3=g3*0;
        }
        
        if(n4>=90){
            jt22.setText("O");
            p4=g4*10;
        }
        else if(n4<90 && n4>=80 ){
            jt22.setText("A+");
            p4=g4*9;
        }
        
        else if(n4<80 && n4>=70 ){
            jt22.setText("A");
            p4=g4*8;
        }
        else if(n4<70 && n4>=60 ){
            jt22.setText("B+");
            p4=g4*7;
        }
        else if(n4<60 && n4>=50 ){
            jt22.setText("B");
            p4=g4*6;
        }
        else if(n4<50 && n4>=40 ){
            jt22.setText("C+");
            p4=g4*5;
        }
        else{
            jt22.setText("E");
            p4=g4*0;
        }
        
        if(n5>=90){
            jt23.setText("O");
            p5=g5*10;
        }
        else if(n5<90 && n5>=80 ){
            jt23.setText("A+");
            p5=g5*9;
        }
       
        else if(n5<80 && n5>=70 ){
            jt23.setText("A");
            p5=g5*8;
        }
        else if(n5<70 && n5>=60 ){
            jt23.setText("B+");
            p5=g5*7;
        }
        else if(n5<60 && n5>=50 ){
            jt23.setText("B");
            p5=g5*6;
        }
        else if(n5<50 && n5>=40 ){
            jt23.setText("C+");
            p5=g5*5;
        }
        else{
            jt23.setText("E");
            p5=g5*0;
        }
        
        if(n6>=90){
            jt24.setText("O");
            p6=g6*10;
        }
        else if(n6<90 && n6>=80 ){
            jt24.setText("A+");
            p6=g6*9;
        }
        
        else if(n6<80 && n6>=70 ){
            jt24.setText("A");
            p6=g6*8;
        }
        else if(n6<70 && n6>=60 ){
            jt24.setText("B+");
            p6=g6*7;
        }
        else if(n6<60 && n6>=50 ){
            jt24.setText("B");
            p6=g6*6;
        }
        else if(n6<50 && n6>=40 ){
            jt24.setText("C+");
            p6=g6*5;
        }
        else{
            jt24.setText("E");
            p6=g6*0;
        }
        
        if(n7>=90){
            jt25.setText("O");
            p7=g7*10;
        }
        else if(n7<90 && n7>=80 ){
            jt25.setText("A+");
            p7=g7*9;
        }
        
        else if(n7<80 && n7>=70 ){
            jt25.setText("A");
            p7=g7*8;
        }
        else if(n7<70 && n7>=60 ){
            jt25.setText("B+");
            p7=g7*7;
        }
        else if(n7<60 && n7>=50 ){
            jt25.setText("B");
            p7=g7*6;
        }
        else if(n7<50 && n7>=40 ){
            jt25.setText("C+");
            p7=g7*5;
        }
        else{
            jt25.setText("E");
            p7=g7*0;
        }
        
        if(n8>=90){
            jt26.setText("O");
            p8=g8*10;
        }
        else if(n8<90 && n8>=80 ){
            jt26.setText("A+");
            p8=g8*9;
        }
        
        else if(n8<80 && n8>=70 ){
            jt26.setText("A");
            p8=g8*8;
        }
        else if(n8<70 && n8>=60 ){
            jt26.setText("B+");
            p8=g8*7;
        }
        else if(n8<60 && n8>=50 ){
            jt26.setText("B");
            p8=g8*6;
        }
        else if(n8<50 && n8>=40 ){
            jt26.setText("C+");
            p8=g8*5;
            
        }
        else{
            jt26.setText("E");
             p8=g8*0;
        }
        res=(p1+p2+p3+p4+p5+p6+p7+p8)/(g1+g2+g3+g4+g5+g6+g7+g8);
        String result = String.format("%.2f",res);
        jt1.setText(result);}}
        jt19.setEditable(false);
        jt20.setEditable(false);
        jt21.setEditable(false);
        jt22.setEditable(false);
        jt23.setEditable(false);
        jt24.setEditable(false);
        jt25.setEditable(false);
        jt26.setEditable(false);
        jt1.setEditable(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //if(jTextfield2.matches("^"))
       // Main1 o1=new Main1();
        if(jTextField2.getText().matches("^[1][2][1][0-9][0-9][0-9][0-9][0-9]$")){
            if(jt1.getText().equals("")){
                JOptionPane.showMessageDialog(null, "GPA not yet calculated", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else{
         Main2 obj=new Main2();
        obj.my_update(jTextField1.getText());
        obj.re(jt1.getText());
        obj.jButton5.setVisible(false);
        obj.jTextField1.setVisible(false);
        obj.jTextField2.setVisible(false);
        
        obj.setVisible(true);
        setVisible(false);}
        }
        else if(jTextField2.getText().matches("^[1][2][2][0-9][0-9][0-9][0-9][0-9]$")){
            if(jt1.getText().equals("")){
                JOptionPane.showMessageDialog(null, "GPA not yet calculated", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else{
            Main2 obj=new Main2();
            obj.my_update(jTextField1.getText());
            obj.re(jt1.getText());
            obj.jButton3.setVisible(false);
        obj.jTextField1.setVisible(false);

        obj.jTextField2.setVisible(false);
        obj.setVisible(true);
        setVisible(false);}
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jt20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt20ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt5ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jt23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt23ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 
                 
                Main1 ob=new Main1();
                ob.jTextField1.setVisible(false);
                ob.jTextField2.setVisible(false);
                ob.setVisible(true);
                
                
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jt1;
    private javax.swing.JTextField jt10;
    private javax.swing.JTextField jt19;
    private javax.swing.JTextField jt20;
    private javax.swing.JTextField jt21;
    private javax.swing.JTextField jt22;
    private javax.swing.JTextField jt23;
    private javax.swing.JTextField jt24;
    private javax.swing.JTextField jt25;
    private javax.swing.JTextField jt26;
    private javax.swing.JTextField jt3;
    private javax.swing.JTextField jt4;
    private javax.swing.JTextField jt5;
    private javax.swing.JTextField jt6;
    private javax.swing.JTextField jt7;
    private javax.swing.JTextField jt8;
    private javax.swing.JTextField jt9;
    // End of variables declaration//GEN-END:variables
}
